// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nncnhgzcttsernsrzwsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY25oZ3pjdHRzZXJuc3J6d3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTYyNTEsImV4cCI6MjA3MjY5MjI1MX0.XkVWOZu8ldO5oCennAu3oETBaJH8a7pJOZMjDWZY-Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});